[package]
name = "rustrest"
version = "0.1.0"
authors = ["Reidar Sollid <rsollid@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = "3.1.7"
poem-openapi = { version = "5.1.5", features = ["sqlx", "swagger-ui"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
# serde = { version = "1.0.214", features = ["derive"] }
tracing-subscriber = "0.3.19"

[dependencies.mongodb]
version = "3.2.1"